service: aws-python-scheduled-cron

frameworkVersion: ">=2.1.1"

provider:
  name: aws
  runtime: python3.7
  region: us-west-2

plugins:
  - serverless-python-requirements

functions:
  cron:
    handler: handler.run
    events:
      # Invoke Lambda function every minute
      - schedule: rate(5 minute)
  secondCron:
    handler: handler.run
    events:
      # Invoke Lambda function Mon-Fri
      - schedule: cron(0/5 13-23 ? * MON-FRI *)
